use_frameworks!

platform :ios, '8.0'

target 'UMQCWorking_Example' do
  pod 'UMQCWorking', :path => '../'

  target 'UMQCWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
