
target 'UMQCWorking_Example' do
  pod 'UMQCWorking', :path => '../'

  target 'UMQCWorking_Tests' do
    inherit! :search_paths
    
    pod 'AFNetworking'
    pod 'WebViewJavascriptBridge'
    pod 'JPush'
    pod 'UMengAnalytics-NO-IDFA'
    pod 'FBSnapshotTestCase'
  end
end
