use_frameworks!

platform :ios, '10.0'
target 'UMQCWorking_Example' do
  pod 'UMQCWorking', :path => '../'

  target 'UMQCWorking_Tests' do
    inherit! :search_paths
    

    pod 'FBSnapshotTestCase'
  end
end
